### ISSUE TITLE
Reading files with backslashes on Windows

### ISSUE THREAD

**Issue by yyan001** [DanuserLab/Biosensor#10]
Hi,

I recently encountered a problem using the BiosensorpackageGUI. When I tried to read a file (i.e. a dark current correction folder) in my local disk, MatLab confused the backslash "\" in the direction with the function "Escape".

I got the setting error "Dark current correction image-D:"

And MatLab gives this warning:

Warning: Escaped character '\D' is not valid. See 'doc sprintf' for supported special characters. 
> In DarkCurrentCorrectionProcess/sanityCheck (line 89)
In darkCurrentCorrectionProcessGUI>pushbutton_done_Callback (line 166)
In gui_mainfcn (line 95)
In darkCurrentCorrectionProcessGUI (line 61)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)darkCurrentCorrectionProcessGUI('pushbutton_done_Callback',hObject,eventdata,guidata(hObject)) 

Do you have any idea how to fix this problem? I tried it on MatLab 2024b and MatLab 2020b. The problem occurs for both versions.

Thank you!

**Comment by DanuserLab** [comment]
Thanks for reaching out, and apologies for the delayed response.
It seems like the issue might actually be due to the mismatch between the dimensions of your dark current images and your raw images. 
Please let us know if this helps or if you need further assistance!
