### ISSUE TITLE
TIF export as 32 bit without scale factor

### ISSUE THREAD

**Issue by GabeK-L** [DanuserLab/Biosensor#11]
Hi Jenny! Can you add an option to export the ratio output as a 32 bit TIF? Or maybe that should be the only option since I think the export as 16 bit with a scale factor of 1000 is only done for historical reasons.

Thanks!

**Comment by DanuserLab** [comment]
Hi Gabe, thank you for your feedback! As per your suggestion, the algorithm for Step 12 Ratio Output has been updated to export TIFs in 32-bit format without applying a scale factor. The revised code has now been pushed to GitHub.
