### ISSUE TITLE
Examples for operation in a headless mode?

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [DanuserLab/Biosensor#6]

**Comment by DanuserLab** [comment]
Thanks for your inquiry regarding Examples for operation in a headless mode. We've provided an illustrative example script in this [issue](https://github.com/DanuserLab/u-probe/issues/3). It's important to note that this script requires careful customization on a case-by-case basis. Additionally, proficiency with our package infrastructure and a comprehensive understanding of MATLAB programming are prerequisites for its successful implementation.
