### ISSUE TITLE
Issues with cropping more than two channels

### ISSUE THREAD

**Issue by mingyu-choi** [DanuserLab/Biosensor#7]
Hello,

I am having issues with the cropping step if my data set has more than two channels. The following message comes up when I try (see attached picture).
![Screenshot (3)](https://github.com/DanuserLab/Biosensor/assets/139798326/0995dd48-76ff-42ee-b55f-2deabe1cd114)

**Comment by DanuserLab** [comment]
Hello Mingyu,

Thank you for reporting the issue. The bug has been successfully addressed, and a fix has been implemented in the latest version released on 12/5/2023. I recommend downloading the updated software from our repository again and giving it another try. If you encounter any further issues or have additional questions, feel free to reach out.

Best regards,
Danuser Lab
